### ISSUE TITLE
Compiler error after updating to 4.0.0

### ISSUE THREAD

**Issue by asaarnak** [flutter-stripe/flutter_stripe#844]
Using Flutter 3.0.5 with Kotlin 1.7.10 and updating to 4.0.0 from 3.3.0 i get this error.

```
Running Gradle task 'assembleDevelopmentDebug'...
e: /home/a/.pub-cache/hosted/pub.dartlang.org/stripe_android-4.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformView.kt: (23, 47): Unresolved reference: CardFieldViewManager
e: /home/a/.pub-cache/hosted/pub.dartlang.org/stripe_android-4.0.0/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformView.kt: (84, 57): Unresolved reference: it

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```
