### ISSUE TITLE
Unresolved reference: style - CardFormView.kt

### ISSUE THREAD

**Issue by ambr89** [flutter-stripe/flutter_stripe#1218]
**Describe the bug**

During the android build I receive an Execution failed:

e: file:///.../.pub-cache/hosted/pub.dev/stripe_android-9.1.0/android/src/main/kotlin/com/reactnativestripesdk/CardFormView.kt:33:71 Unresolved reference: style

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**To Reproduce**
I use:

 - Android Studio Flamingo | 2022.2.1
 - Upgrade my main project gradle to 8.0.0 with AGP Tool 
 - change build.gradle into stripe_android-9.1.0 package
 ```
...
android {
    compileSdkVersion 32
    namespace 'com.flutter.stripe'

    def javaVersion = JavaVersion.VERSION_1_8
    compileOptions {
        sourceCompatibility javaVersion
        sourceCompatibility javaVersion
    }
    kotlinOptions {
        jvmTarget = javaVersion.toString()
    }
...
 ```
  These changes are needed to try to compile with Flamingo and Java 1.8

I've tried with version 8.0.0+1, 9.0.0+1 and 9.1.0 and always I get this error.
Thanks in advance.
Ambra

**Comment by jonasbark** [comment]
Can you provide an example project where this is reproducible?

**Comment by ambr89** [comment]
Hi,

yes you can clone the project from here:
[https://github.com/ambr89/test_prj](https://github.com/ambr89/test_prj)

The difference from your documentation is:

in gradle-wrappre.properties:

distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip

**Comment by ambr89** [comment]
Hi,

no, the error on update  9.2.0 is the same. 

```
e: /Users/ambra/.pub-cache/hosted/pub.dev/stripe_android-9.2.0/android/src/main/kotlin/com/reactnativestripesdk/CardFormView.kt: (33, 71): Unresolved reference: style

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

**Comment by ambr89** [comment]
Hi,

any news about this?

**Comment by jonasbark** [comment]
No news. It's best to use a compatible gradle version for now, if that's the only difference for you.

**Comment by ambr89** [comment]
Hi,

no problem I've found a solution because I cannot downgrade gradle in my project.

Here there are changes for work with gradle 8.0 and above:

**In stripe_android-9.2.0/android/build.gradle**

```
android {
    namespace 'com.flutter.stripe'
    compileSdkVersion 32

   //Add this code block
    def javaVersion = JavaVersion.VERSION_1_8
    compileOptions {
        sourceCompatibility javaVersion
        sourceCompatibility javaVersion
    }
    kotlinOptions {
        jvmTarget = javaVersion.toString()
    }
…

}
```



**in stripe_android-9.2.0/android/src/main/kotline/com/reactnativestripesdk/CardFormView.kt**

change this:
```
internal var cardForm: CardFormView = CardFormView(context, null, R.style.StripeCardFormView_Borderless
```
with:
```
internal var cardForm: CardFormView = CardFormView(context)
```

just with this you can test plugin in debug mode,

for build release apk or appbundle add also this:

**In stripe_android-9.2.0/android/proguard-rules.txt** 

```
# add this to the end of file
-dontwarn com.google.android.libraries.places.api.Places
-dontwarn com.google.android.libraries.places.api.model.AddressComponent
-dontwarn com.google.android.libraries.places.api.model.AddressComponents
-dontwarn com.google.android.libraries.places.api.model.AutocompletePrediction
-dontwarn com.google.android.libraries.places.api.model.AutocompleteSessionToken
-dontwarn com.google.android.libraries.places.api.model.Place$Field
-dontwarn com.google.android.libraries.places.api.model.Place
-dontwarn com.google.android.libraries.places.api.model.TypeFilter
-dontwarn com.google.android.libraries.places.api.net.FetchPlaceRequest
-dontwarn com.google.android.libraries.places.api.net.FetchPlaceResponse
-dontwarn com.google.android.libraries.places.api.net.FindAutocompletePredictionsRequest$Builder
-dontwarn com.google.android.libraries.places.api.net.FindAutocompletePredictionsRequest
-dontwarn com.google.android.libraries.places.api.net.FindAutocompletePredictionsResponse
-dontwarn com.google.android.libraries.places.api.net.PlacesClient
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivity$g
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Args
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Error
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningEphemeralKeyProvider
-dontwarn com.stripe.android.stripecardscan.cardscan.CardScanSheet$CardScanResultCallback
-dontwarn com.stripe.android.stripecardscan.cardscan.CardScanSheet$Companion
-dontwarn com.stripe.android.stripecardscan.cardscan.CardScanSheet
-dontwarn com.stripe.android.stripecardscan.cardscan.CardScanSheetResult$Completed
-dontwarn com.stripe.android.stripecardscan.cardscan.CardScanSheetResult$Failed
-dontwarn com.stripe.android.stripecardscan.cardscan.CardScanSheetResult
-dontwarn com.stripe.android.stripecardscan.cardscan.exception.UnknownScanException
-dontwarn com.stripe.android.stripecardscan.payment.card.ScannedCard
```

**Comment by ilDeffo** [comment]
Hi,
any news on this issue? I am experiencing the same problem

**Comment by derekpitts28** [comment]
Bump

**Comment by remonh87** [comment]
not reproducible anymore
