### ISSUE TITLE
Execution failed for task ':stripe_android:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by princeflutterdev** [flutter-stripe/flutter_stripe#887]
**Describe the bug**
flutter_stripe: ^4.0.0 

C:\development\Flutter-Latest\.pub-cache\hosted\pub.dartlang.org\stripe_android-4.0.0\android\src\main\kotlin\com\facebook\react\bridge\ReactApplicationContext.java:8: error: cannot find symbol
import com.flutter.stripe.StripeAndroidPlugin;
                         ^
  symbol:   class StripeAndroidPlugin
  location: package com.flutter.stripe
C:\development\Flutter-Latest\.pub-cache\hosted\pub.dartlang.org\stripe_android-4.0.0\android\src\main\kotlin\com\facebook\react\bridge\ReactApplicationContext.java:25: error: cannot find symbol
    public void addActivityEventListener(@NotNull BaseActivityEventListener activityEventListener) {
                                                  ^
  symbol:   class BaseActivityEventListener
  location: class ReactApplicationContext
C:\development\Flutter-Latest\.pub-cache\hosted\pub.dartlang.org\stripe_android-4.0.0\android\src\main\kotlin\com\facebook\react\uimanager\events\Event.java:11: error: cannot find symbol

**Smartphone / tablet**
 - Device: [Redmi Note 10S]
 - OS: [Android 12]
 - Package version: [4.0.0]
 - Flutter version [3.0.5]

**Comment by remonh87** [comment]
Did you check you comply to all requirements stated here? Use Kotlin version 1.5.0 and above: [example](https://github.com/flutter-stripe/flutter_stripe/blob/79b201a2e9b827196d6a97bb41e1d0e526632a5a/example/android/ .gradle

Our app compiles on version 4.0 so it should be something in your setup

**Comment by remonh87** [comment]
For android support please ask your questions here: https://github.com/flutter-stripe/flutter_stripe/discussions/538

**Comment by Rushi-Gandhi** [comment]
I've successfully resolved the "Task :stripe_android:compileDebugJavaWithJavac FAILED" error by adding the following dependency override in my project:

```yaml
dependency_overrides:
  stripe_android: "9.5.0+1"
```

This adjustment worked for me. Feel free to give it a try and let me know if it resolves the issue on your end as well.

**Comment by Reshma5560** [comment]
Execution failed for task ':stripe_android:compileDebugJavaWithJavac'.
> error: invalid source release: 17

I gort this error if i am using 
 flutter_stripe: ^10.0.0 
 
IMAGE :( https://prnt.sc/KUg5LD0gorvq )

**Comment by hamzaali163** [comment]
This is package has many limitations, it should be improved.
