### PR TITLE
fix: serialize nested flat payment element config

### LINKED ISSUE #2431: EmbeddedPaymentElement with RadioConfig throws Invalid argument: Instance of '_RadioConfig'
### ### Describe the bug

FlatConfig.toJson() emits its nested children (radio, checkmark, disclosure) as raw objects instead of serializing them. When an EmbeddedPaymentElement appearance with a RadioConfig is sent to native over the platform channel, StandardMessageCodec can't encode the raw object and throws Invalid argument: Instance of '_RadioConfig'.

To Reproduce

Render EmbeddedPaymentElement with:

```
appearance: const PaymentSheetAppearance(
  embeddedPaymentElement: EmbeddedPaymentElementAppearance(
    row: RowConfig(
      style: RowStyle.flatWithRadio,
      flat: FlatConfig(
        radio: RadioConfig(
          selectedColor: Colors.blue,
          unselectedColor: Colors.white,
        ),
      ),
    ),
  ),
)
```
The element fails to load with:

Invalid argument: Instance of '_RadioConfig'
#0 StandardMessageCodec.writeValue (message_codecs.dart:464)
Expected behavior

FlatConfig.toJson() serializes radio/checkmark/disclosure so the appearance applies without crashing.

Smartphone

Device: Android (Dart-side serialization bug — platform-independent)
OS: Android 16
Package version: flutter_stripe 13.0.0
Flutter version: 3.44.0
Additional context

CheckmarkConfig and DisclosureConfig are affected the same way.

### PR DESCRIPTION
**Pull request by MrTONYCHAN**
## Summary

- serialize nested `FlatConfig` appearance objects before sending them through Flutter's platform channel
- cover separator insets, radio, checkmark, and disclosure configurations
- add a regression test for the complete nested JSON payload

Without explicit nested serialization, `StandardMessageCodec` receives generated Dart objects such as `_RadioConfig` and throws `Invalid argument`.

Fixes #2431.

## Validation

- `flutter test test/payment_sheet_serialization_test.dart` — passed
- `flutter analyze lib/src/models/payment_sheet.dart test/payment_sheet_serialization_test.dart` — passed
- `git diff --check` — passed

The full package test command currently stops on an unrelated existing null-safety compilation error in `test/test_data.dart` where nullable `Multibanco` fields are accessed without null checks. The new targeted regression test passes independently.

## Checklist

- [x] Have you followed the guidelines in our [Contributing](https://github.com/flutter-stripe/flutter_stripe/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/flutter-stripe/flutter_stripe/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Do all checks pass?
- [x] Have you developed the feature on the latest stable version of Flutter?

- [x] AI was used to generate or assist with generating this PR.

## AI disclosure

OpenAI Codex assisted with repository inspection, implementation, test generation, and drafting this PR description. I reviewed the generated diff, regenerated the checked-in Freezed/json_serializable outputs, ran the targeted regression test and analyzer, checked for competing pull requests, and verified the final commit before submission.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved payment sheet appearance serialization for nested and optional configuration values.
  * Ensured inset and color settings are converted correctly when exported to JSON.

* **Tests**
  * Added coverage verifying nested payment sheet appearance configurations serialize with the expected keys and values.

### CODE REVIEW

**Review by remonh87 — APPROVED** [review]
thanks!
