### PR TITLE
Fix #1022

### LINKED ISSUE #1022: Cannot build with Version 7.0.0
Here's log : 

> `e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\stripe_android-7.0.0\android\src\main\kotlin\com\reactnativestripesdk\Mappers.kt: (453, 3): 'when' expression must be exhaustive, add necessary 'UpiAwaitNotification' branch or 'else' branch instead
e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\stripe_android-7.0.0\android\src\main\kotlin\com\reactnativestripesdk\utils\Mappers.kt: (458, 3): 'when' expression must be exhaustive, add necessary 'UpiAwaitNotification' branch or 'else' branch instead

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':stripe_android:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 47s
Exception: Gradle task assembleDebug failed with exit code 1
`

### PR DESCRIPTION
**Pull request by asaarnak**
See #1022 
Fixes Kotlin error.

### CODE REVIEW

**Comment by remonh87** [comment]
Thanks I fixed it using the exact Stripe mapper code so we remain in sync 👍 . CLosing this one for now
