### ISSUE TITLE
Cannot build with Version 7.0.0 

### ISSUE THREAD

**Issue by zakblacki** [flutter-stripe/flutter_stripe#1022]
Here's log : 

> `e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\stripe_android-7.0.0\android\src\main\kotlin\com\reactnativestripesdk\Mappers.kt: (453, 3): 'when' expression must be exhaustive, add necessary 'UpiAwaitNotification' branch or 'else' branch instead
e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\stripe_android-7.0.0\android\src\main\kotlin\com\reactnativestripesdk\utils\Mappers.kt: (458, 3): 'when' expression must be exhaustive, add necessary 'UpiAwaitNotification' branch or 'else' branch instead

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':stripe_android:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 47s
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by remonh87** [comment]
I would recommend to run `flutter clean` first and then run again. Also make sure that you have gradle 7.4 or higher

**Comment by tamirrab** [comment]
Same here,
Using gradle 7.4
Done flutter clear

**Comment by geosebas** [comment]
Same here, first time I tried to use flutter_stripe.
When you say "gradle 7.4", do you guys mean the version of android gradle plugin is 7.4 or gradle version is 7.4 ? Currently using android studio dolphin and it doesn't support 7.4+ android gradle.

Done multiple time flutter clean and flutter pub get too

**Comment by geosebas** [comment]
Okay managed to build by reverting to an older kotlin version (1.6.21). Starting with Kotlin 1.7.0, we get theses build errors.

So for me I managed to build with : 
- Kotlin : 1.6.21 (see android/build.gradle)
- Android gradle plugin : 7.2.2 (see android/build.gradle)
- Gradle: 7.4 (see android/gradle/wrapper/gradle-wrapper.properties)


PS : I still got an 'note' when building : 
```
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-7.0.0\android\src\main\kotlin\com\facebook\react\uimanager\DisplayMetricsHolder.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by jonasbark** [comment]
Thanks for the ticket - Kotlin newer than 1.6.21 is indeed not supported at the moment

**Comment by asaarnak** [comment]
Since July 2022 Kotlin 1.7.10, 1.7.20, 1.7.21 has worked for us.
This error appears with flutter-stripe 7.0.0.
Reverting to flutter-stripe 6.0.0 also works.

**Comment by asaarnak** [comment]
Created PR #1024 
Using my fork while waiting for fix.

dependency_overrides:
  stripe_android:
    git:
      url: https://github.com/asaarnak/flutter_stripe
      ref: patch-2
      path: packages/stripe_android

**Comment by remonh87** [comment]
I think it is related to https://github.com/stripe/stripe-react-native/pull/1195

Will try to implement a fix tomorrow (quite busy today).

**Comment by remonh87** [comment]
fix in stripe android 7.0.1

**Comment by zakblacki** [comment]
Please note this is also recurrent with building on ios it doesn't specify why or where

**Comment by remonh87** [comment]
@zakblacki  if you have problems with ios feel free to open a new issue
