### ISSUE TITLE
Compilation error in 11.5.0

### ISSUE THREAD

**Issue by cufano** [flutter-stripe/flutter_stripe#2132]
**Describe the bug**
I get a compilation error when update the package to 11.5.0

**To Reproduce**
1. Update pubspec.yaml to flutter_stripe: ^11.0.0
2. flutter pub get
3. When running it in the iOS Simulator you get the error:
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/stripe_platform_interface-11.5.0/lib/src/models/color.dart:23:18: Error: The getter 'r' isn't defined for the class 'Color'.

**Expected behavior**
I expect to run without errors

**Smartphone / tablet**
 - Device: iOS Simulator
 - OS: iOS 15.4.1
 - Package version: 11.5.0
 - Flutter version 3.24.3

**Comment by davemg3** [comment]
Same thing with  flutter_stripe: ^11.4.0 and  flutter_stripe: ^11.5.0
 flutter_stripe: ^11.5.1 is not yet available on https://pub.dev/
@jonasbark , could you say how long before being able to see it available?
thk u

**Comment by Williamtobs** [comment]
This is not fixed yet
